### ISSUE TITLE
Is there any solution to sink Protobuf message from Kafka topic to Azure Data Explorer?

### ISSUE THREAD

**Issue by ConfieBlake** [Azure/kafka-sink-azure-kusto#112]
We do not have schema registry. We would like to configure the Kafka Connector with our compiled protobuf class, so that the message could also use the Kusto sink to ingest data into ADX. Do you have any idea how to make it happen?

**Comment by ag-ramachandran** [comment]
there is no direct support for protobuf. But there are ways to get it to work. You can refer the steps and config from the article -

https://techcommunity.microsoft.com/t5/azure-data-explorer-blog/ingesting-protobuf-data-from-kafka-to-azure-data-explorer/ba-p/3595793
