### ISSUE TITLE
Is there support for Schema Registry with Protobuf?

### ISSUE THREAD

**Issue by kewitschka** [Azure/kafka-sink-azure-kusto#124]
The docs say that schema registry only supports avro and json: https://github.com/Azure/kafka-sink-azure-kusto?tab=readme-ov-file#35-schema-registry

On the other hand it says that ProtobufConverter is supported. Does it support Schema Registry with Protobuf or not?

**Comment by ag-ramachandran** [comment]
Hello @kewitschka , there is no direct support for protobuf. But there are ways to get it to work. You can refer the steps and config from the article - 

https://techcommunity.microsoft.com/t5/azure-data-explorer-blog/ingesting-protobuf-data-from-kafka-to-azure-data-explorer/ba-p/3595793
