### ISSUE TITLE
how to connect to Azure china kusto

### ISSUE THREAD

**Issue by jiangzheng51** [Azure/kafka-sink-azure-kusto#20]
in the /var/log/broker.log /var/log/connect-distributed.log
I found errorlog like "...TenantId not found in Subscriptions..." 
But my TenantId is right
how to change the azure locaiton to china azure

**Comment by anagha-microsoft** [comment]
Can you please email me your scenario and detailed issues and logs to ankhanol@microsoft.com?  Thanks.

**Comment by ohadbitt** [comment]
The authority url should be provided as an environment variable with the name 'AadAuthorityUri'. By default we use this url- “https://login.microsoftonline.com/”

**Comment by jiangzheng51** [comment]
Thank

We've solved it

发件人: ohad bitton <notifications@github.com>
发送时间: 2020年7月7日 22:39
收件人: Azure/kafka-sink-azure-kusto <kafka-sink-azure-kusto@noreply.github.com>
抄送: jiang.zheng <jiang.zheng@cn.nssol.nipponsteel.com>; Author <author@noreply.github.com>
主题: Re: [Azure/kafka-sink-azure-kusto] how to connect to Azure china kusto (#20)


The authority url should be provided as an environment variable with the name 'AadAuthorityUri'. By default we use this url- “https://login.microsoftonline.com/”<https://login.microsoftonline.com/%E2%80%9D>
