### ISSUE TITLE
Data Client does not cater for private Kusto URL while validating Table access

### ISSUE THREAD

**Issue by Langfo** [Azure/kafka-sink-azure-kusto#39]
We use a private URL to connect to Kusto.  The Data Client connection code in createKustoEngineClient() does not cater for private URLs.

At line 99 in KustoSinkTask.java 

`String engineClientURL = config.getKustoUrl().replace("https://ingest-", "https://");`

This could be changed to test for a private url

`
String engineClientURL = config.getKustoUrl().contains("private") ?
                    config.getKustoUrl().replace("https://private-ingest-", "https://private-") :
                    config.getKustoUrl().replace("https://ingest-", "https://");
`

**Comment by yihezkel** [comment]
Thanks for bringing this to our attention! This is being addressed in PR #40 

In the meantime, a workaround is to use for a private URL:
https://ingest-private-[cluster].kusto.windows.net

Instead of:
https://private-ingest-[cluster].kusto.windows.net

**Comment by anagha-microsoft** [comment]
Thanks @yihezkel.  @Langfo, we have a workaround that we tested successfully, so this wont block you.  Will update you when we release a patch.

**Comment by anagha-microsoft** [comment]
Closing issue as it is not blocking.  Docs are updated to reflect workaround.  A strategic fix is in development.
