### ISSUE TITLE
FETCH_TABLE_QUERY  result throws exception due to being cast to int.

### ISSUE THREAD

**Issue by Langfo** [Azure/kafka-sink-azure-kusto#41]
In the KustoSinkTask.java file, the code checks access to the configured ADX table using the kusto query **"%s|count"** contained in the variable FETCH_TABLE_QUERY.  We currently have over 25 billion rows in our table so when this value is cast to an int it fails.

Could you please either change the code in KustoSinkTask.java at line 260 to cast to a long
 
`
if ((long) rs.getPrimaryResults().getData().get(0).get(0) >= 0) {
`

or else could you just change the query to ensure a valid integer is returned

`
static final String FETCH_TABLE_QUERY = "%s|limit 1|count";
`

Thanks.

**Comment by anagha-microsoft** [comment]
@Langfo - thanks for bringing this to our attention.  We are fixing this ASAP.
