### ISSUE TITLE
Add support for Single Message Transforms (SMTs)

### ISSUE THREAD

**Issue by AskMeiPaaS** [Azure/kafka-sink-azure-kusto#58]
The Kafka Connect API also provides a simple interface for manipulating records as they flow through both the source and sink side of your data pipeline. This API is known as Single Message Transforms (SMTs), and as the name suggests, it operates on every single message in your data pipeline as it passes through the Kafka Connect connector.

Some common uses for transforms are:

- Renaming fields
- Masking values
- Routing records to topics based on a value
- Converting or inserting timestamps into the record
- Manipulating keys, like setting a key from a field’s value

**Comment by ohadbitt** [comment]
Hi
SMTs are part of Kafka connect platform and not of the sink
you can look here for an example of how to integrate it 
https://github.com/microsoft/kafka-connect-cosmosdb/blob/b5e29740bd53cc0f9d9688e50c8961eb8580a163/doc/README_Sink.md#single-message-transforms

**Comment by yogilad** [comment]
Closing
