### ISSUE TITLE
Avro source

### ISSUE THREAD

**Issue by destasys** [Azure/kafka-sink-azure-kusto#6]
I am utilizing the Microsoft kutso (ADX) connector but not able to use an avro source topic ... https://github.com/Azure/kafka-sink-azure-kusto/blob/master/src/main/java/com/microsoft/azure/kusto/kafka/connect/sink/TopicPartitionWriter.java#L76 , the value type is https://kafka.apache.org/11/javadoc/org/apache/kafka/connect/data/Schema.Type.html#STRUCT so it gives me an error any ideas?

src/main/java/com/microsoft/azure/kusto/kafka/connect/sink/TopicPartitionWriter.java:76
            log.error(String.format("Unexpected value type, skipping record %s", value));
<https://github.com/Azure/kafka-sink-azure-kusto|Azure/kafka-sink-azure-kusto>Azure/kafka-sink-azure-kusto | Added by GitHub

**Comment by ohadbitt** [comment]
sorry for the late reply
avro format is available only since last version
follow the instructions in the docs (i will update these very soon to explain better this process)

**Comment by ohadbitt** [comment]
https://github.com/Azure/kafka-sink-azure-kusto/pull/9
