### ISSUE TITLE
Potential NPE in TopicPartitionWriter

### ISSUE THREAD

**Issue by preston-m-price** [Azure/kafka-sink-azure-kusto#62]
This case will yield a NPE if a null record is passed in.

https://github.com/Azure/kafka-sink-azure-kusto/blob/6dbd611a0fbad324cc27430ed3a61fe5e447c8b4/src/main/java/com/microsoft/azure/kusto/kafka/connect/sink/TopicPartitionWriter.java#L205-L207

I tried to push a PR to fix but I'm blocked, so I'll start by opening an issue.

**Comment by ohadbitt** [comment]
fix on #63 
2.3.0
