### ISSUE TITLE
Timer threads can cause duplicates during rebalance

### ISSUE THREAD

**Issue by preston-m-price** [Azure/kafka-sink-azure-kusto#69]
We're seeing this behavior fairly regularly when we update the topics and topic mappings for a connector.

During a rebalance the connect runtime will perform these steps in order:
1. Get the offsets to commit by calling [preCommit](https://github.com/apache/kafka/blob/84b41b9d3ad4b45a9137197a304996759e993cde/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/WorkerSinkTask.java#L404).
2. Close the topic partitions by invoking [close](https://github.com/apache/kafka/blob/84b41b9d3ad4b45a9137197a304996759e993cde/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/WorkerSinkTask.java#L421).
3. [Commit the offsets](https://github.com/apache/kafka/blob/84b41b9d3ad4b45a9137197a304996759e993cde/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/WorkerSinkTask.java#L460) retrieved in step 1.

If a timer thread runs between/during steps 1 and 2 we end up pushing messages to kusto AFTER the offsets have been calculated in `preCommit`. Then after the rebalance the new SinkTask will pick up where kafka thinks we left off, which would be the last committed offsets and we'll get duplicates.

More in depth example:
1: KustoSinkTask.open() is invoked for a single TopicPartition which delegates to TopicPartitionWriter.open() and a new FileWriter is created.
2: KustoSinkTask.put() is invoked for a set of messages with offsets 90-100. The underlying FileWriter opens a file and starts a timer thread: https://github.com/Azure/kafka-sink-azure-kusto/blob/6dbd611a0fbad324cc27430ed3a61fe5e447c8b4/src/main/java/com/microsoft/azure/kusto/kafka/connect/sink/FileWriter.java#L246-L247
Messages with offsets 90-100 are written to the file.
3: A rebalance starts
4: KustoStinkTask.preCommit() is invoked and since we have not committed a file yet the `lastCommittedOffset` for the TopicPartitionWriter will be null so we do not provide an offset to commit for this TopicPartition.
5: The timer thread runs and we upload the file containing offsets 90-100.
6: KustoSinkTask.close() is invoked
7: The offsets calculated in KustoSinkTask.preCommit() are committed (no-op in this case).
https://github.com/apache/kafka/blob/84b41b9d3ad4b45a9137197a304996759e993cde/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/WorkerSinkTask.java#L425-L428
8: KustoSinkTask.open() is invoked for our TopicPartition after its (re)assigned to a task.
9: We resume from the last committed offsets and KustoSinkTask.put() is invoked with the same offsets starting at 90 again.
10: Through flush, or rolling file size we publish a file containing offsets 90-100 again and introduce dupes to our destination.

There are some strategies for handling dupes on Kusto (Materialized Views for example). However there is overhead associated with those strategies, and not sending duplicates at all would be desirable.

Using this pattern of FlushTimers I do not see a way to avoid the scenario described above because there is no way to determine a rebalance from a [normal timed offset commit](https://github.com/apache/kafka/blob/84b41b9d3ad4b45a9137197a304996759e993cde/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/WorkerSinkTask.java#L218). During a rebalance we would want to cancel the flush timers before calculating the offsets to commit to ensure we could not publish files after the offsets were calculated.
There are other defects I've reported around the behavior of the flush timers (https://github.com/Azure/kafka-sink-azure-kusto/issues/64, https://github.com/Azure/kafka-sink-azure-kusto/issues/65) and I wonder if it would be a better pattern to leverage the flush() behavior to publish files on an interval rather than introduce the complexities and edge cases that the timer threads introduce? Is there a reason that `flush` is not being used in favor of the flush timers? By default `offset.flush.interval.ms` is 60 seconds ([docs](https://docs.confluent.io/platform/current/connect/references/allconfigs.html)), and perhaps tuning that property to achieve the periodic flush of pending files by time would simplify things?

**Comment by ohadbitt** [comment]
We use flush timers in order to support flushing by time intervals
This means that if a user set the flush size to sime mbs but there was not enough data during this i terval we would still ingest
