### ISSUE TITLE
Connector stopped working with error: Bootstrap broker (id: -1 rack: null) disconnected

### ISSUE THREAD

**Issue by roicostas** [Azure/kafka-sink-azure-kusto#77]
Kusto sink connector stopped working and all task ( 4 ) continuously output this error but do not ingest anything else in dataexplorer:

WARN [Producer clientId=connector-dlq-producer-<connector_name>-<task_id>] Bootstrap broker <host>:<port> (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)

Any idea about what is going on? here is the connector configuration:

{
        "connector.class": "com.microsoft.azure.kusto.kafka.connect.sink.KustoSinkConnector",
        "aad.auth.appid": "\*\*\*",
        "aad.auth.appkey": "\*\*\*",
        "tasks.max": "4",
        "basic.auth.credentials.source": "USER_INFO",
        "errors.deadletterqueue.security.protocol": "SASL_SSL",
        "value.converter.basic.auth.credentials.source": "USER_INFO",
        "flush.size.bytes": "10000000",
        "errors.deadletterqueue.sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"\*\*\*\" password=\"\*\*\*\";",
        "kusto.query.url": "\*\*\*",
        "value.converter": "io.confluent.connect.avro.AvroConverter",
        "config.action.reload": "restart",
        "kusto.tables.topics.mapping": "[{'topic': '\*\*\*','db': '\*\*\*', 'table': '\*\*\*','format': 'avro', 'mapping':'\*\*\*', 'streaming':'false'}]",
        "key.converter": "org.apache.kafka.connect.storage.StringConverter",
        "errors.deadletterqueue.bootstrap.servers": "\*\*\*",
        "kusto.ingestion.url": "\*\*\*",
        "errors.deadletterqueue.sasl.mechanism": "PLAIN",
        "flush.interval.ms": "5000",
        "aad.auth.authority": "\*\*\*",
        "topics": "\*\*\*",
        "behavior.on.error": "log",
        "topics.regex": "",
        "value.converter.schema.registry.url": "\*\*\*",
        "basic.auth.user.info": "\*\*\*",
        "value.converter.basic.auth.user.info": "\*\*\*",
        "errors.deadletterqueue.topic.name": "\*\*\*.dlq",
        "name": "\*\*\*"
    }

We currently have two kafka connect workers which are not too busy

**Comment by tanmaya-panda1** [comment]
Hi @roicostas, the log seems to be a warning log about some network connectivity issue. Can you please help us with mote logs regarding the same.

**Comment by roicostas** [comment]
Hi @tanmaya-panda1, it was a missconfiguration in the kafka connect producer of the worker. Although dead letter topic should have enought configuration to produce data to the topic, worker producer has to be configured too.
